config/routes.rb
Rails.application.routes.draw do
   get 'root/index'
   get 'done' => 'warehouses#done'
   root to: 'root#index'

   devise_for :users
   get   'users/mypage'   =>  'users#show'    #Mypageへのルーティング
   resources :reservations
   resources :warehouses
   resources :items

   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
   has_many :reservations_users
   has_many :users, through: :reservations_users
   belongs_to :warehouse

   has_many :reservations_warehouses
   has_many :warehouses, through: :reservations_warehouses

   def change_start(params)
      start=params[:reservation]
      time = start['start(1i)']+'-'+start['start(2i)']+'-'+start['start(3i)']+' '+start['start(4i)']+':'+start['start(5i)']
      return start=DateTime.parse(time)
   end

   def change_end(params)
      endtime=params[:reservation]
      time = endtime['end(1i)']+'-'+endtime['end(2i)']+'-'+endtime['end(3i)']+' '+endtime['end(4i)']+':'+endtime['end(5i)']
      return endtime=DateTime.parse(time)
   end

   class Item < ActiveRecord::Base
      mount_uploader :image, ImageUploader
   end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
   before_action :set_reservation, only: [:show, :edit, :update, :destroy]
   before_action :move_to_index, except: :index

   # GET /reservations
   # GET /reservations.json
   def index
      # n+1問題の解消のためにいつか変更
      @reservations = Reservation.all.order("created_at DESC").page(params[:page]).per(5)
      @warehouses = Warehouse.all
   end

   # GET /reservations/1
   # GET /reservations/1.json
   def show
   end

   # GET /reservations/new
   def new
      @reservation = Reservation.new
   end

   # GET /reservations/1/edit
   def edit
      @reservation = Reservation.find(params[:id])
      starttime = @reservation.change_start(params)
      endtime = @reservation.change_end(params)
   end

   # POST /reservations
   # POST /reservations.json
   def create
      @reservation = Reservation.new()
      starttime = @reservation.change_start(params)
      endtime = @reservation.change_end(params)
      respond_to do |format|
         if Reservation.create(start: starttime, end: endtime, user_id: current_user.id, item_id: 1, warehouse_id: params.require(:reservation)['warehouse_id'])
            format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
            format.json { render :show, status: :created, location: @reservation }
         else
            format.html { render :new }
            format.json { render json: @reservation.errors, status: :unprocessable_entity }
         end
      end
   end

   # PATCH/PUT /reservations/1
   # PATCH/PUT /reservations/1.json
   def update
      respond_to do |format|
         if Reservation.update(start: starttime, end: endtime, user_id: current_user.id, item_id: 1, warehouse_id: params.require(:reservation)['warehouse_id'])
         # if @reservation.update(reservation_params)　元のコード
            format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
            format.json { render :show, status: :ok, location: @reservation }
         else
            format.html { render :edit }
            format.json { render json: @reservation.errors, status: :unprocessable_entity }
         end
      end
   end

   # DELETE /reservations/1
   # DELETE /reservations/1.json
   def destroy
      @reservation.destroy
      respond_to do |format|
         format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
         format.json { head :no_content }
      end
   end

   private
   # Use callbacks to share common setup or constraints between actions.
   def set_reservation
      @reservation = Reservation.find(params[:id])
   end

   # Never trust parameters from the scary internet, only allow the white list through.
   def reservation_params
      params.require(:reservation).permit(Reservation::REGISTRABLE).merge(user_id: 1, item_id: 1, warehouse_id: 1)
   end

   def move_to_index
      redirect_to action: :index unless user_signed_in?
   end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
<% if reservation.errors.any? %>
<div id="error_explanation">
   <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

   <ul>
      <% reservation.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
   </ul>
</div>
<% end %>

<div class="field">
   <%= form_for @reservation do |f| %>
   <label class="control-label" for="">荷物数</label>
   <select name="example">
      <option value="選択肢1">冷蔵庫 x 1</option>
      <option value="選択肢2">冷蔵庫 x 2</option>
      <option value="選択肢3">冷蔵庫 x 3</option>
      <option value="選択肢4">冷蔵庫 x 4</option>
      <option value="選択肢5">冷蔵庫 x 1000</option>
   </select>

   <label class="control-label" for="">チェックイン</label>
   <%= f.datetime_select :startdate, {}, class: 'form-control' %>

   <label class="control-label" for="">チェックアウト</label>
   <%= f.datetime_select :enddate, {}, class: 'form-control' %>

   <% end %>

</div>


<div class="actions">
   <%= form_for @reservation do |f| %>
   <%= f.submit "予約する", class: "" %>
   <% end %>
</div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<!-- <%= render 'form', reservation: @reservation %> -->
<div class="wrapper-field">
   <%= form_tag("/reservations/#{@reseravtion.id}", method: :patch ) do %>
   <h3>
      編集する
   </h3>
   <!-- <input placeholder="Image Url" type="text" name="image" value="<%= @tweet.image %>" autofocus="true"> -->
   <%= f.datetime_select :startdate, {}, class: 'form-control' %>
   <%= f.datetime_select :enddate, {}, class: 'form-control' %>
   <input type="submit" value="SENT">
   <% end %>
</div>


<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<div class="alert alert-warning" role="alert">
   <p id="notice"><%= notice %></p>
</div>

<div class="wrapper-field">
   <h1><%= @email %>さんの予約一覧</h1>
</div>

<table>
   <thead>
      <tr>
         <th colspan="3"></th>
      </tr>
   </thead>

   <tbody>
      <% @reservations.each do |reservation| %>
      <div class="row">
         <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
               <!-- <img src="" alt=""> -->
               <div class="caption wrapper-field">
                  <h4>倉庫名：<%= reservation.warehouse.name %></h4>
                  <p>チェックイン：<%= reservation.start.strftime("%Y年%m月%d日 %H時%M分") %></p>
                  <p>チェックアウト<%= reservation.end.strftime("%Y年%m月%d日 %H時%M分") %></p>
                  <p>
                     <%= link_to '詳細へ', reservation , class: "btn btn-warning form-control", role: "button" %>
                  </p>
                  <p>
                     <!-- <%= link_to '編集する', edit_reservation_path(reservation), class: "btn btn-warning form-control", role: "button" %> -->
                     <%= link_to '編集する', "/reservations/#{reservation.id}/edit", class: "btn btn-warning form-control", role: "button" %>
                  </p>
                  <p>
                     <%= link_to '取り消す', reservation, method: :delete, data: { confirm: '本当に予約を取り消しますか？'}, class: "btn btn-warning form-control", role: "button" %>
                  </p>
                  <br>
               </div>
            </div>
         </div>
      </div>
      <% end %>
   </tbody>
</table>
<%= paginate(@reservations) %>
<div class="wrapper-field">
<%= link_to 'さらに予約する', new_reservation_path, class: "btn btn-warning form-control", role: "button" %>
</div>

app/views/reservations/new.html.erb
<h1>予約画面</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to '戻る', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>