config/routes.rb
Rails.application.routes.draw do
   get 'root/index'
   get 'done' => 'warehouses#done'
   root to: 'root#index'

   devise_for :users
   get   'users/mypage'   =>  'users#show'    #Mypageへのルーティング
   resources :reservations
   resources :warehouses
   resources :items

   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
   before_action :set_warehouse, only: [:show, :edit, :update, :destroy]

   # GET /warehouses
   # GET /warehouses.json
   def index
      @warehouses = Warehouse.all
      @hash = Gmaps4rails.build_markers(@warehouses) do |warehouse, marker|
         marker.lat warehouse.latitude
         marker.lng warehouse.longitude
         # marker.infowindow warehouse.description
         marker.infowindow render_to_string( partial: "warehouses/infowindow",
            locals: { warehouse: warehouse} )
            marker.json({name: warehouse.name})
         end
      end
      # GET /warehouses/1
      # GET /warehouses/1.json
      def show
         @warehouses = Warehouse.find(params[:id])
         @hash = Gmaps4rails.build_markers(@warehouses) do |warehouse, marker|
            marker.lat warehouse.latitude
            marker.lng warehouse.longitude
            # marker.infowindow warehouse.description
            marker.json({name: warehouse.name})
            @reservation = Reservation.new
         end
      end

      def done
         @warehouse = Warehouse.limit(1).order("created_at DESC")
         @hash = Gmaps4rails.build_markers(@warehouses) do |warehouse, marker|
            marker.lat warehouse.latitude
            marker.lng warehouse.longitude
            # marker.infowindow warehouse.description
            marker.json({name: warehouse.name})
         end
      end

      # GET /warehouses/new
      def new
         @warehouse = Warehouse.new
      end

      # GET /warehouses/1/edit
      def edit
      end

      # POST /warehouses
      # POST /warehouses.json
      def create
         @warehouse = Warehouse.new(warehouse_params)
         respond_to do |format|
            if @warehouse.save
               format.html { redirect_to :action=>'done', notice: 'Warehouse was successfully created.' }
               format.json { render :show, status: :created, location: @warehouse }
            else
               format.html { render :new }
               format.json { render json: @warehouse.errors, status: :unprocessable_entity }
            end
         end
      end

      # PATCH/PUT /warehouses/1
      # PATCH/PUT /warehouses/1.json
      def update
         respond_to do |format|
            if @warehouse.update(warehouse_params)
               format.html { redirect_to @warehouse, notice: 'Warehouse was successfully updated.' }
               format.json { render :show, status: :ok, location: @warehouse }
            else
               format.html { render :edit }
               format.json { render json: @warehouse.errors, status: :unprocessable_entity }
            end
         end
      end

      # DELETE /warehouses/1
      # DELETE /warehouses/1.json
      def destroy
         @warehouse.destroy
         respond_to do |format|
            format.html { redirect_to warehouses_url, notice: 'Warehouse was successfully destroyed.' }
            format.json { head :no_content }
         end
      end

      private
      # Use callbacks to share common setup or constraints between actions.
      def set_warehouse
         @warehouse = Warehouse.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def warehouse_params
         params.require(:warehouse).permit(:name, :adress, :price)
      end

   end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/warehouses/_form.html.erb
<%= form_for @warehouse do |f| %>
<% if warehouse.errors.any? %>
<div id="error_explanation">
   <h2><%= pluralize(warehouse.errors.count, "error") %> prohibited this warehouse from being saved:</h2>

   <ul>
      <% warehouse.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
   </ul>
</div>
<% end %>

<div class="wrapper-field">
   <%= f.label :倉庫名 %><br />
   <%= f.text_field :name, class: "form-control"%>
</div>
<div class="wrapper-field">
   <%= f.label :住所 %><br />
   <%= f.text_field :adress, class: "form-control" %>
</div>
<div class="wrapper-field">
   <%= f.label :価格 %><br />
   <%= f.number_field :price, class: "form-control" %>
</div>
<div class="center wrapper-field">
   <%= f.submit "登録する", class: "btn btn-warning form-control" %>
</div>
<% end %>

app/views/warehouses/_infowindow.html.erb
<div>
  <%= link_to "#{warehouse.name}", warehouse %>
</div>

app/views/warehouses/done.html.erb
<p id="notice"><%= notice %></p>

<div style='width: 375px;'>
  <div id="map" style='width: 375px; height: 300px;'></div>
</div>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
</script>
<%= @warehouse[0].name %>

<!-- <%= link_to '編集する', edit_warehouse_path(@warehouse) %> | -->
<%= link_to '戻る', warehouses_path %>

app/views/warehouses/edit.html.erb
<h1>Editing Warehouse</h1>

<%= render 'form', warehouse: @warehouse %>

<%= link_to 'Show', @warehouse %> |
<%= link_to 'Back', warehouses_path %>

app/views/warehouses/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->


<!-- <table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @warehouses.each do |warehouse| %>
      <tr>
        <td><%= link_to 'Show', warehouse %></td>
        <td><%= link_to 'Edit', edit_warehouse_path(warehouse) %></td>
        <td><%= link_to 'Destroy', warehouse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<div style='width:  375px;'>
  <div id="map" style='width: 375px; height: 600px;'></div>
</div>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });

    Gmaps.store = {}
    Gmaps.store.markers = markers.map(function(m) {
      marker = handler.addMarker(m);
      marker.serviceObject.set('id', m.id);
      marker.serviceObject.set('infowindow', m.infowindow);
      return marker;
   });

      google.maps.event.addListener(handler.getMap(), "open", function(id) {
  $.each(Gmaps.store.markers, function() {
    if (this.serviceObject.id == id) {
      infowindow = new google.maps.InfoWindow({
        content: this.serviceObject.infowindow
      });
      infowindow.open(this.serviceObject.map, this.serviceObject);
    }
  });
});
</script>

<br>

<%= link_to 'New Warehouse', new_warehouse_path %>

app/views/warehouses/new.html.erb
<h1>荷物の登録</h1>

<%= render 'form', warehouse: @warehouse %>

<%= link_to 'Back', warehouses_path %>

app/views/warehouses/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div style='width: 375px;'>
   <div id="map" style='width: 375px; height: 300px;'></div>
</div>

<!-- <div id="map" class="img-responsive"></div> -->

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
   markers = handler.addMarkers(<%=raw @hash.to_json %>);
   handler.bounds.extendWith(markers);
   handler.fitMapToBounds();
});
</script>
<div class="wrapper-field">
   <h4>倉庫名：<%= @warehouse.name %></h4>
   <br>
   <%= form_for @reservation do |f| %>
   <%= f.text_field :warehouse_id, value: "#{params['id']}", class: 'hidden' %>
   <!-- <label class="control-label" for="">荷物数</label> -->
   <div>
      <label class="control-label" for="">チェックイン</label>
      <div>
         <%= f.datetime_select :start, {}, class: 'form-control bootstrap-date', use_month_numbers: true %>
      </div>
   </div>

   <div>
      <label class="control-label" for="">チェックアウト</label>
      <div>
         <%= f.datetime_select :end, {}, class: 'form-control bootstrap-date' %>
      </div>

      <div class="wrapper-field">
         <%= f.submit "予約する", class: 'form-control btn btn-warning' %>
      </div>
   </div>
   <% end %>

</div>


<!-- <%= link_to '編集する', edit_warehouse_path(@warehouse) %> | -->
<!-- <%= link_to '戻る', warehouses_path %> -->